### PR TITLE
Fix/5 crash on pods selection

### LINKED ISSUE #5: Killing program on pod selection results in an error
```
goproxie                                                                                                                                                                                                                                          
? Choose project: <project>
? Choose proxy type: POD
? Choose cluster:  [Use arrows to move, type to filter]
> <cluster>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5614a8]

goroutine 1 [running]:
github.com/AckeeCZ/goproxie/internal/gcloud.GetClusterCredentials(...)
	/home/smolijar/go/src/github.com/AckeeCZ/goproxie/internal/gcloud/cli.go:39
main.main()
	/home/smolijar/go/src/github.com/AckeeCZ/goproxie/main.go:234 +0x148
```

### PR DESCRIPTION
**Pull request by smoliji**
- make main routine testable
- add tests for main routine
- add empty checks for no project id etc and exit with a meaningful message

Fixes #5

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -249,20 +263,36 @@ func main() {
...
+		fmt.Println("Could not find any GCP Clusters")
+		return
+	}
 	if proxyType == "POD" {
 		loadingStart("Loading Cluster credentials")
-		gcloud.GetClusterCredentials(projectID, cluster)
+		gcloudGetClusterCredentials(projectID, cluster)
 		loadingStop()
 		namespace := readNamespace()
+		if namespace == "" {
```
Comment (sandratatarevicova) [inline main.go:281]: In which case do we return an empty string as namespace? Wouldn't it be nicer to return `nil` so that it is consistent with `readCluster()` and `readPod()`? The same applies to `readProjectID()`.

Comment (smoliji) [reply main.go:281]: In an empty case.

`readNamespace` returns `string`, not `* string` (means I cannot assign `nil` to a `string` value). Proposed solution would require refactoring those functions. Which can be done in another PR. The same applies to  `readProjectID()`.
